### ISSUE TITLE
现在还在做这个吗？

### ISSUE THREAD

**Issue by dududiao** [zhongxia245/weiqunkong#1]
我也想搞一下这个，请教下。qq：465706121

**Comment by zhongxia245** [comment]
这个目前没有维护，因为目前的实现有两大问题没有搞定
- [ ]  如何控制多台手机（超过12台，32台，64台， 等），目前只能6台一下
- [ ] 操作如何更流畅（PC操作手机，手机屏幕映射到PC的流程度）

这两个问题Java目前实现起来效果不太好
